import { useRouter } from "next/router";
import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";

import { PhoneIcon, MailIcon, CakeIcon, LocationMarkerIcon, UserCircleIcon } from "@heroicons/react/outline";

import Header from "../../components/Header";
import Footer from "../../components/Footer";
import PostList from "../../components/Post/PostList";
import { useState, useEffect } from "react";

const UserProfile: NextPage = () => {
  const [opacity, setOpacity] = useState("opacity-0");
  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    setOpacity("opacity-100");
  }, []);
  return (
    <div className="bg-slate-50 p-6 sm:p-8">
      <Head>
        <title>User Profile - Prueba - misfans</title>
        <meta name="User Profile Prueba para misfans" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`transition-opacity duration-300 ease-in ${opacity}`}>
        <Header />
        <div className="flex flex-col justify-center items-center">
          <div className="flex flex-col p-2 sm:p-4">
            <div className="flex flex-row justify-center items-center flex-wrap p-2">
              <Image
                className="rounded-full"
                layout="fixed"
                src="https://images.ctfassets.net/lh3zuq09vnm2/yBDals8aU8RWtb0xLnPkI/19b391bda8f43e16e64d40b55561e5cd/How_tracking_user_behavior_on_your_website_can_improve_customer_experience.png"
                width={180}
                height={180}
              />
              <div className="flex flex-col justify-between p-1 sm:p-6">
                <div className="m-3">
                  <h1 className="text-4xl text-gray-800 font-bold my-1">Mr. Rudi Droste</h1>
                  <p className="text-sm text-gray-400">60d0fe4f5311236168a109ce</p>
                </div>
                <div className="flex flex-row text-gray-400">
                  <div className="flex flex-row m-1 items-center">
                    <CakeIcon className="h-5 w-5  mx-1" />
                    <p className="text-sm ">Apr 30</p>
                  </div>
                  <div className="flex flex-row m-1 items-center">
                    <UserCircleIcon className="h-5 w-5  mx-1" />
                    <p className="text-sm t">Female</p>
                  </div>
                  <div className="flex flex-row m-1 items-center">
                    <LocationMarkerIcon className="h-5 w-5  mx-1" />
                    <p className="text-sm ">Denmark</p>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-row justify-center items-center py-1 sm:py-4">
              <a
                href="mailto: sara.andersen@example.com"
                className="flex flex-row m-1 items-center transition ease-in duration-200 text-yellow-600 hover:text-yellow-700 ">
                <MailIcon className="h-5 w-5 mx-1" />
                <p className="text-sm ">sara.andersen@example.com</p>
              </a>
              <a
                href="tel:92694011"
                className="flex flex-row m-1 items-center transition ease-in duration-200 text-yellow-600 hover:text-yellow-700">
                <PhoneIcon className="h-5 w-" />
                <p className="text-sm">92694011</p>
              </a>
            </div>
          </div>
          <PostList />
        </div>
        <Footer />
      </div>
    </div>
  );
};

export default UserProfile;
