import type { NextPage } from "next";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";

import Header from "../components/Header";
import Footer from "../components/Footer";
import UserList from "../components/User/UserList";

const Home: NextPage = () => {
  const [opacity, setOpacity] = useState("opacity-0");
  const router = useRouter();

  useEffect(() => {
    setOpacity("opacity-100");
  }, []);

  const goToUserProfile = (href: string) => {
    setOpacity("opacity-0");
    setTimeout(() => router.push(href), 300);
  };

  return (
    <div className="bg-slate-50 p-8">
      <Head>
        <title>User List - Prueba - misfans</title>
        <meta name="Prueba para misfans" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`transition-opacity duration-300 ease-in ${opacity}`}>
        <Header />
        <UserList goToUserProfile={goToUserProfile} />
        <Footer />
      </div>
    </div>
  );
};

export default Home;
