import { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import Header from "../components/Header";
import Footer from "../components/Footer";
import Link from "next/link";

const NotFound: NextPage = () => {
  const [opacity, setOpacity] = useState("opacity-0");

  useEffect(() => {
    setOpacity("opacity-100");
  }, []);

  return (
    <div className="bg-slate-50 p-4 sm:p-8">
      <Head>
        <title>User Not Found - Prueba - misfans</title>
        <meta name="User Profile Prueba para misfans" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`transition-opacity duration-300 ease-in ${opacity}`}>
        <Header />
        <div className="h-screen flex flex-col justify-center items-center ">
          <h1 className="text-gray-800 text-6xl font-bold">404 Not Found</h1>
          <Link href="/">
            <button className="border shadow rounded text-gray-400 text-2xl font-bold m-4 px-6 py-2">Go Home</button>
          </Link>
        </div>

        <Footer />
      </div>
    </div>
  );
};

export default NotFound;
